[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
switchboard_oracle = "8zFhh2V3NGTezMo4ZEA6mU66UnAbuKgrQNykTxzghoYC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "6bsjqFVARhNJewHY5YAVGZGaHAujaf3DMEUtgNkZNvbw"

[[test.validator.clone]]
address = "SBondMDrcV3K4kxZR1HNVT7osZxAHVHgYXL5Ze1oMUv"

[[test.validator.clone]]
address = "7txSqq4TiKCPA1h9xXwPjfjHFE8ZW5xdXRxvDjkKwhpJ"

[[test.validator.clone]]
address = "26jBLWF5TFe5cuKcSUuw7oq96fq5FkYWnbUMRUFCqAuy"
